// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6nC3-49nect-t12hy3mg01_SN36Azk4g',
    appId: '1:469319439099:web:71aa22199266ae2e2bd65e',
    messagingSenderId: '469319439099',
    projectId: 'my-sosecure-project',
    authDomain: 'my-so-project.firebaseapp.com',
    storageBucket: 'my-sosecure-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBF7HU5Ux5FzRK94zEjlX1DfnO3Dje5SM',
    appId: '1:469319439099:android:ac81981deb0948e42bd65e',
    messagingSenderId: '469319439099',
    projectId: 'my-sosecure-project',
    storageBucket: 'my-sosecure-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG2_RE70Q9jMIRRWYnKgqaV3sUE8SNk8o',
    appId: '1:469319439099:ios:49e13d9f3bc9e68a2bd65e',
    messagingSenderId: '469319439099',
    projectId: 'my-sosecure-project',
    storageBucket: 'my-sosecure-project.firebasestorage.app',
    iosBundleId: 'com.example.sosecure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG2_RE70Q9jMIRRWYnKgqaV3sUE8SNk8o',
    appId: '1:469319439099:ios:49e13d9f3bc9e68a2bd65e',
    messagingSenderId: '469319439099',
    projectId: 'my-sosecure-project',
    storageBucket: 'my-sosecure-project.firebasestorage.app',
    iosBundleId: 'com.example.sosecure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6nC3-49nect-t12hy3mg01_SN36Azk4g',
    appId: '1:469319439099:web:318126183e4308e12bd65e',
    messagingSenderId: '469319439099',
    projectId: 'my-sosecure-project',
    authDomain: 'my-so-project.firebaseapp.com',
    storageBucket: 'my-sosecure-project.firebasestorage.app',
  );
}
